### ISSUE TITLE
Setting options via configuration file

### ISSUE THREAD

**Issue by iMashtak** [iMashtak/cvto#5]
Simple file with keys/values, may be any format which supported for conversion. Toml example:

```toml
[java-properties]
ser.kv-separator = ": "
````

Should be able to provide via cli option or automatically apply if exists in current working directory. Cli options will override values from config.
